title: Dayton Chevalier # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Here I maintain a code repository for interview purposes.
  <br><br>
  <a href="www.linkedin.com/in/dayton-chevalier">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
